#!/bin/sh -e

# wipe away any previous builds
rm -fr dist

# make sure libraries used for publishing are up to date
pipenv run python3 -m pip install --upgrade setuptools wheel twine
pipenv run python3 -m pip install --upgrade twine

pipenv run python3 setup.py sdist
