#!/bin/sh -e

DEBUG_DRF_MORE=true pipenv run python3 test/mysite/manage.py makemigrations

DEBUG_DRF_MORE=true pipenv run python3 test/mysite/manage.py migrate

DEBUG_DRF_MORE=true pipenv run python3 test/mysite/manage.py runserver
